name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Sync project to server
        run: |
          rsync -az --delete -e "ssh -o StrictHostKeyChecking=no" ./ \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/nosmoke-bot

      - name: Rebuild & restart containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} <<'SSH'
            cd /root/nosmoke-bot
            docker compose pull
            docker compose up -d --build
SSH
